# Add compilation flags here. 
CFLAGS   := -g -Ldeps
SRCFILES := $(wildcard src/*.c)
OBJFILES := $(addprefix obj/, $(notdir $(SRCFILES:.c=.o)))
DEPFILES := $(addprefix obj/, $(notdir $(SRCFILES:.c=.d)))

# Links all the object files, builds the game to the bin directory.
bin/game: $(OBJFILES) | bin
	$(CC) $(CFLAGS) -o bin/game $(OBJFILES) -l:libglfw3.a -lm

obj: 
	mkdir obj

bin:
	mkdir bin

clean: 
	rm -rf obj 
	rm -rf bin

# Rule for building object files. Also build dependency files.
obj/%.o: src/%.c | obj 
	$(CC) $(CFLAGS) -I deps -MMD -c $< -o $@ 

# Include dependency files generated by the above step.
# This effectively adds new prerequisites to each object file rule 
# (the header files it depends on).
-include $(DEPFILES)

.PHONY: clean
